name: Build Android APK

on:
  workflow_dispatch:
    inputs:
      app_name:
        description: 'Name of the App'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2

      - name: Accept Licenses
        run: yes | sdkmanager --licenses

      - name: Install Build Tools
        run: sdkmanager "platform-tools" "platforms;android-33" "build-tools;33.0.0"

      - name: Replace app name
        run: sed -i "s/APP_NAME_PLACEHOLDER/${{ github.event.inputs.app_name }}/g" android-template/app/src/main/res/values/strings.xml

      - name: Build APK
        run: ./gradlew assembleDebug
        working-directory: android-template

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: chatbot-apk
          path: android-template/app/build/outputs/apk/debug/app-debug.apk
