name: Build APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Code checkout
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      # Gradlew ko execute permission dena
      - name: Give Gradlew permission
        working-directory: android-template
        run: chmod +x gradlew

      # Debug APK build karna
      - name: Build Debug APK
        working-directory: android-template
        run: ./gradlew assembleDebug

      # APK upload karna
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-debug
          path: android-template/app/build/outputs/apk/debug/app-debug.apk
