name: Build Android APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Give gradlew permission
        run: chmod +x android-template/gradlew

      - name: Build Debug APK
        run: |
          cd android-template
          ./gradlew assembleDebug --stacktrace --info

      - name: Find all APK files
        run: |
          echo "🔍 Searching for APK files..."
          find . -name "*.apk"

      - name: Upload APK if exists
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: android-template/app/build/outputs/apk/debug/app-debug.apk
