name: Build Android APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Setup Java
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3. Check repo files (Debugging help)
      - name: List repository files
        run: ls -R

      # 4. Gradlew permission
      - name: Give gradlew permission
        run: chmod +x android-template/gradlew

      # 5. Build APK
      - name: Build Debug APK
        run: |
          cd android-template
          ./gradlew assembleDebug --stacktrace --info

      # 6. Upload generated APK
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: android-template/app/build/outputs/apk/debug/app-debug.apk
