name: Build APK without Gradle

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt || true

      - name: Run Python build script
        run: python app.py

      - name: Find APK files
        run: |
          mkdir -p apks
          find android-template/app -name "*.apk" -exec cp {} apks/ \;

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: APKs
          path: apks/
